### ISSUE TITLE
Login Page looks weird

### ISSUE THREAD

**Issue by medmin** [laraveluk/website#160]
https://laravelphp.uk/login

This page, i guess, is supposed to look like the sign up page, but apparently, it looks weird.

I am not a front end developer or a web designer, so i have no PR. 

Sorry. 

I just want you guys to know about this issue. Thanks.

**This page looks weird on Chrome but it's good on Edge**

**My Chrome is Chrome Version 67.0.3396.99 (Official Build) (64-bit)**

**Comment by stevepop** [comment]
Hi @medmin The page looks okay to me on Chrome (Mac) Can you show us a screen shot of what you are seeing? Please screenshot in my Chrome for Mac.
![image](https://user-images.githubusercontent.com/526063/42055050-ebc76b46-7b0d-11e8-8191-d013fd6bda8d.png)

**Comment by stevepop** [comment]
Thanks @medmin I will check on a Windows browser as well.

**Comment by leecrosdale** [comment]
![image](https://user-images.githubusercontent.com/12886732/42058229-ac50601c-7b17-11e8-8eae-b333ffed3b83.png)
It's fine on mine however, the issue for @medmin is caused because the nav bar moves over the top of the login section, they should both move together.

**Comment by leecrosdale** [comment]
![image](https://user-images.githubusercontent.com/12886732/42058281-d4f670a6-7b17-11e8-9cf9-9a9f4b7e236b.png)
You can accomplish the same issue by making your browser window smaller
