### ISSUE TITLE
Adhoc oAuth error when using sign in with slack button

### ISSUE THREAD

**Issue by mradamwood** [laraveluk/website#171]
Seems to happen when someone is already signed into another slack workspace - can replicate.

When not logged into another workspace the workspace url isn't pre-filled so I'm wondering if something is missing from setup?

**Comment by mradamwood** [comment]
The team parameter is empty - thought that might have something to do with. Will have a play and see.

**Comment by stevepop** [comment]
@mradamwood For some reason I can't find that setting in our Slack account. Probably only available for paid accounts? I have checked but can't find any settings like that relating the the LaravelUK Signup with Slack application

**Comment by leecrosdale** [comment]
I'm not sure I did the Slack auth, I definitely did the Slack invitation though.

@stevepop that setting should be there on the app, I don't think it needs to be paid for,

**Comment by mradamwood** [comment]
I'd totally forgotten I was going to look at this. Will try and get round to it. Sorry!

**Comment by leecrosdale** [comment]
@mradamwood as discussed we should just make the url [here](https://laravelphp.uk/slack) available with some nice looking frontend, that way users don't have to register to the site in order to get an invitation.
