### ISSUE TITLE
Backend Blog User Flow

### ISSUE THREAD

**Issue by MadMikeyB** [laraveluk/website#65]
Backend Blog Index should defer to the Frontend Blog Index

When creating a new blog post, you should be redirected to /blog/{slug} on the front end, not on the back end.

All the back end needs is /members/#/blog/create and /members/#/blog/SLUG (for editing and deletion).

**Comment by leecrosdale** [comment]
Just to confirm, if I create a blog post named 'test-test' once I post the data, you want it to redirect to {site}/blog/test-test instead of {site}/members/#/blog/test-test

**Comment by MadMikeyB** [comment]
@leecrosdale yes - I was just going to start on working on this bit now. Unless you already have?
