### ISSUE TITLE
Navigation needs streamlining

### ISSUE THREAD

**Issue by MadMikeyB** [laraveluk/website#66]
We have a front end nav and back end nav.

In a perfect world these would become one partial, which is used for both.

When you are not logged in you see the login button, when you are logged in you see the login button. This all needs to be changed to be more dynamic.

I'd like to defer to the `<navbar>` vue component.

**Comment by joepriest** [comment]
We could have two includes - one for authenticated users and one for guests - would that work?

**Comment by stevepop** [comment]
The reason we have both is that the frontend Nav is blade while the backend Nav is a Vue component. We could use a global Nav component in this case

**Comment by MadMikeyB** [comment]
I think we should use a Vue Component everywhere and ditch the Blade nav.

**Comment by joepriest** [comment]
We have a globally accessible user object now (thanks @MadMikeyB for the idea!) so that should make it easier

**Comment by stevepop** [comment]
This has now been implemented in PR #68
