### ISSUE TITLE
Prevent other users from editing/deleting other posts

### ISSUE THREAD

**Issue by simondavies** [laraveluk/website#82]
At the moment when any user log's in, they cannot only edit a post but also delete the post.  We should ensure that ONLY the post's creator and/or a moderator/admin are able to edit these.

So there is a need to add some form of permission role system.

I'm not sure what your goals are for the site, with regards to users freedom,  but there should still be some form or moderation applied to the submission of content, especially for legal reasons.

**Comment by stevepop** [comment]
Hi @simondavies, I agree totally and we are definitely going to work on this ASAP.

**Comment by simondavies** [comment]
No worries thought best to mention it, so its visually there for ref. :-)

**Comment by stevepop** [comment]
Policies now implemented in PR https://github.com/laraveluk/website/pull/84
