### ISSUE TITLE
Enhancement: Add metadata details to a new/edit post

### ISSUE THREAD

**Issue by simondavies** [laraveluk/website#99]
The way that the page produces the metadata is to use the current post title.  This is wrong, as its displaying the title for both title and description. Also, the facebook metadata formation is also wrong.

I suggest further updating the post create/edit to incorporate an Excerpt section.  Which will be text only so no wysiwyg editor but a plain textarea. 

As well as feeding the post listings excerpts copy, we could then use this to feed the metadata description fields.

Also reformatting the metadata from within the main page views to a partial, so that it's just the one file and there for as the site grows prevents us from updating several pages. Also adding further metadata to include twitter.

I am willing to work on this section if needs be.

an example would be switchin out:

```html
<title>LaravelUK - {{$post->title}}</title>
    <meta name="title" content="LaravelUK - {{$post->title}}" />
    <meta name="description" content="LaravelUK - {{$post->title}}" />
    <meta name="og_title" content="LaravelUK - {{$post->title}}" />
    <meta name="og_description" content="LaravelUK - {{$post->title}}" />
````

for 
`partials/metadata.blade.php`

```html
       <title>{!!$post->title!!}</title>
       <link rel="canonical" href="{{ URL::current() }}">

       <meta name="title" content="{!!$post->title!!}" />
       <meta name="description" content="{!!$post->title!!}" />
        <meta itemprop="image" content="/imgs/socials/twitter-share-image.jpg">

        <meta property="og:type" content="website">
        <meta property="og:url" content="{{ URL::current() }}">
        <meta property="og:title" content=""{!!$post->title!!}">
        <meta property="og:image" content="/imgs/socials/facebook-share-image.jpg">
        <meta property="og:description" content=""{!!$post->excerpt!!}">
        <meta property="og:site_name" content="Laravel UK">
        <meta property="og:locale" content="en_GB" />
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">

        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="@UKLaravel}">
        <meta name="twitter:creator" content="@UKLaravel}">
        <meta name="twitter:url" content="{{ URL::current() }}">
        <meta name="twitter:title" content=""{!!$post->title!!}">
        <meta name="twitter:description" content=""{!!$post->excerpt!!}">
        <meta name="twitter:image" content="/imgs/socials/twitter-share-image.jpg">

````
There's a few more metatags that can be used but the above is just an example. :-)

**Comment by stevepop** [comment]
@simondavies I have assigned this task to you. Thanks!

**Comment by simondavies** [comment]
@stevepop  Thanks will let you know once I have things to review and approve.
